# Generated automatically from Makefile.in by configure.
ALL: default
##### User configurable options #####

ARCH        = sun4
COMM        = ch_p4
BOPT        = 
P4_DIR      = 
TOOLS_DIR   = 
MPIR_HOME   = /Net/antireo/antireo6/lusk/mpich
CC          = cc
CLINKER     = cc
CCC         = 
CCLINKER    = $(CCC)
F77         = f77
FLINKER     = $(F77)
AR          = ar clr
RANLIB      = ranlib
PROFILING   = $(PMPILIB)
OPTFLAGS    = -g
LIB_PATH    = -L/Net/antireo/antireo6/lusk/mpich/lib/sun4/ch_p4 
LIB_LIST    = -lmpi 
#
INCLUDE_DIR =  -I$(MPIR_HOME)/include 
DEVICE      = ch_p4

### End User configurable options ###

CFLAGS  =   $(OPTFLAGS) $(INCLUDE_DIR) -DMPI_$(ARCH)
CCFLAGS = $(CFLAGS)
#FFLAGS = '-qdpc=e' 
FFLAGS = $(OPTFLAGS)
MPILIB = $(MPIR_HOME)/lib/$(ARCH)/$(COMM)/libmpi.a 
MPIPPLIB = $(MPIR_HOME)/lib/$(ARCH)/$(COMM)/libmpi++.a
LIBS = $(LIB_PATH) $(LIB_LIST)
LIBSPP = $(MPIPPLIB) $(LIBS)
EXECS = overtake sendrecv isndrcv third fourth fifth sixth hvectest \
	hvectest2 probe probe1 testtest1 testtypes ssendtest typetest\
	secondf

default: $(EXECS)

testing: default
	  runtests

linktest: sendrecv secondf clean

all: testing

overtake: overtake.o test.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o overtake overtake.o test.o $(LIBS)

sendrecv: sendrecv.o test.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o sendrecv sendrecv.o test.o $(LIBS)

isndrcv: isndrcv.o test.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o isndrcv isndrcv.o test.o $(LIBS)

typetest: typetest.o test.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o typetest typetest.o test.o $(LIBS)

ssendtest: ssendtest.o test.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o ssendtest ssendtest.o test.o $(LIBS)

testtypes: testtypes.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o testtypes testtypes.o $(LIBS)

third: third.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o third $(DEVICE_MAIN) third.o $(LIBS)
fourth: fourth.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o fourth $(DEVICE_MAIN) fourth.o $(LIBS)
fifth: fifth.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o fifth $(DEVICE_MAIN) fifth.o $(LIBS)
sixth: sixth.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o sixth $(DEVICE_MAIN) sixth.o $(LIBS)

probe: probe.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o probe $(DEVICE_MAIN) probe.o $(LIBS)

probe1: probe1.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o probe1 $(DEVICE_MAIN) probe1.o $(LIBS)

testtest1: testtest1.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o testtest1 $(DEVICE_MAIN) testtest1.o $(LIBS)

hvectest: hvectest.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o hvectest $(DEVICE_MAIN) hvectest.o $(LIBS)

hvectest2: hvectest2.o $(MPIR_HOME)/include/mpir.h $(MPILIB)
	$(CLINKER) $(OPTFLAGS) -o hvectest2 $(DEVICE_MAIN) hvectest2.o $(LIBS)

secondf: secondf.o mpif.h
	$(FLINKER) $(OPTFLAGS) -o secondf secondf.o $(LIBS)

mpif.h: $(MPIR_HOME)/include/mpif.h
	ln -s $(MPIR_HOME)/include/mpif.h .


clean:
	/bin/rm -f *.o *~ PI* $(EXECS) pt2pt.out pt2pt.out.orig secondf

.c.o:
	$(CC) $(CFLAGS) -c $*.c
.f.o:
	$(F77) $(FFLAGS) -c $*.f

