#! /bin/sh
#
# This script derives the p4 routines from the Chameleon ones.  Some editing 
# of the files may be required after this process, but the goal is to 
# fully automate this process.
#
sed -e '/#define DEVICE_CHAMELEON/d' \
    -e 's/MPID_CH_/MPID_P4_/g' \
    -e 's/"Chameleon"/"p4"/g' ../chameleon/dmch.h > dmp4.h
sed -e 's/MPID_CH_/MPID_P4_/g' ../chameleon/mpid_bind.h > mpid_bind.h
sed -e 's/MPID_CH_/MPID_P4_/g' ../chameleon/packets.h > packets.h
sed -e 's/MPID_CH_/MPID_P4_/g' ../chameleon/channel.h > channel.h
sed -e 's/MPID_CH_/MPID_P4_/g' ../chameleon/mpiddebug.h > mpiddebug.h
sed -e 's/MPID_CH_/MPID_P4_/g' ../chameleon/mpidstat.h > mpidstat.h
for file in event hetero recv send init probe sync rndv coll debug ; do 
    ../chameleon/rmget ../chameleon/ch$file.c | \
	../chameleon/rmchameleon > p4$file.c
    chmod ug+w p4$file.c
done
chmod ug+w *.[ch]
/home/gropp/tools.n/bin/inlinecomm -main -quiet -p4 p4init.c
for file in p4event.c p4recv.c p4send.c p4probe.c p4sync.c p4coll.c dmp4.h \
	p4rndv.c p4debug.c p4hetero.c packets.h channel.h ; do
    /home/gropp/tools.n/bin/inlinecomm -quiet -p4 $file
done
#
# Change the names MPID_CH to MPID_P4
/bin/rm -f .tmp
for file in p4*.c ; do
    sed -e 's/MPID_CH_/MPID_P4_/g' $file > .tmp
    mv .tmp $file
done
