#!/bin/csh
# $1 is previous MPI P4;  $2 NEW (non-MPI) p4
rm -rf $2/{README,CHANGES,DISCLAIMER}
rm -rf $2/{contrib,contrib_f,doc,lib_f,messages_f,misc,monitors}
cd $1
cp Makefile ../$2
foreach dir ([a-z]*)
    cp $dir/makefile.proto ../$2/$dir
end
cd ..
cat <<.
You also need to change util/defs.all to have

CFLAGS = -g -I$$(INCLUDEDIR) -I../../../../include $$(MDEP_CFLAGS) $$(USER_CFLAGS)

in the COMMON section, and lib/p4_MD.h to have

#ifndef LINT
#define  P4_INCLUDED
#include "mpisys.h"
#define p4_malloc(size) MALLOC(size)
#define p4_free(p) FREE(p)
#define p4_clock MD_clock
#endif

near the end of the file.

Also, remove the 

extern P4VOID exit();

from the end of lib/p4_MD.h (some systems define as int exit()).

.

Next, make sure that p4_MD.c has 

#if defined(SGI) && defined(VENDOR_IPC)

before the call to usfree() (older versions has SOLARIS).

Next, add

typedef long P4_Aint;

to p4_error.c, and globally change (int) to (P4_Aint) (WITH the parenthesis,
that is, make that casts use P4_Aint, not int).


