.TH Chameleon-MPI 5 "8/23/1995" " " "ADI"
.SH NAME
Chameleon-MPI transport (device) implementation

This simple Chameleon implementation is meant to work with
most message passing systems and does not rely on large amounts
of message buffering.  Messages are sent in one or two packets, depending
on the length.  If the message is short (< 
.I MPID_PKT_DATA_SIZE
), then
the header and message are placed into a single message and sent
together.  Long messages are sent without copying the message by
sending the header in a separate packet.

This Chameleon implementation depends on adequate buffering by the
message-passing system.  Because there is no asynchronous notification
of messages in Chameleon (because most transport layers do not provide
this important functionality), it is difficult to implement a
packet-based system (i.e., one that divides messages into multiple
packets and manages all buffering).

.SH COMMENTS ON THE IMPLEMENTATION

There are many things that can be done to improve the performance of
the implementation of the ADI on various platforms.  Some of these
have been added to the current implementation with ifdef''s (see the
MPICH configure for more discussion of what is currently available).

