.TH MPID_Dest_byte_order 5 "8/23/1995" " " "ADI"
.SH NAME
MPID_Dest_byte_order \- Returns the byte ordering desired by the
destination

.SH INPUT PARAMETER
.PD 0
.TP
.B dest 
- Absolute rank or destination
.PD 1

.SH RETURNS
One of 
.I MPID_H_NONE
, 
.I MPID_H_LSB
, 
.I MPID_H_MSB
, 
.I MPID_H_XDR


.SH SYNOPSIS
.nf
int MPID_Dest_byte_order( int dest )
.fi

