.TH MPID_Test_send 5 "10/10/1994" " " "ADI"
.SH NAME
MPID_Test_send \- Tests for the completion of a send request

.SH INPUT PARAMETER
.PD 0
.TP
.B ctx 
- ADI context returned by MPID_Init
.PD 1
.PD 0
.TP
.B dmpi_send_handle 
- API's send handle
.PD 1

.SH RETURN VALUE
True (!= 0) if the request has completed, False (0) otherwise.

.SH NOTES
Unimplemented at present
