.TH MPID_HAS_HETERO 5 "8/23/1995" " " "ADI"
.SH NAME
MPID_HAS_HETERO \- Indicates that heterogeneous processors may be present

.SH NOTES
This is a macro that is defined when the ADI supports heterogeneous
processing elements.  APIs that are to operate in a heterogeneous
environment need to ensure that message are properly prepared.
See also the discussion on heterogeneous support, 
.I MPID_IS_HETERO

