.TH MPID_Blocking_send 5 "10/10/1994" " " "ADI"
.SH NAME
MPID_Blocking_send \- Performs a blocking send

.SH INPUT PARAMETER
.PD 0
.TP
.B ctx 
- ADI context returned by MPID_Init
.PD 1
.PD 0
.TP
.B dmpi_send_handle 
- API's send handle
.PD 1

.SH SYNOPSIS
.nf
int MPID_Blocking_send( void * ctx, MPIR_SHANDLE *dmpi_send_handle )
.fi

