.TH MPID_Wtime_is_global 5 "8/23/1995" " " "ADI"
.SH NAME
MPID_Wtime_is_global \- Returns the resolution of the timer 
.I MPID_Wtime


.SH RETURN VALUE
True (1) if the value from 
.I MPID_Wtime
 is synchronized on all processes,
False (0) otherwise.

.SH SYNOPSIS
.nf
int MPID_Wtime_is_global( void )
.fi

.SH NOTES
This is often implemented with a definition
.nf
#define MPID_Wtime_is_global() 1
.fi

If this is not defined, it is assumed that 
.I MPID_Wtime
 is not
synchronized.

