.TH MPID_Post_send_ready 5 "8/23/1995" " " "ADI"
.SH NAME
MPID_Post_send_ready \- Starts a send of a message with ready mode

.SH INPUT PARAMETER
.PD 0
.TP
.B ctx 
- ADI context returned by 
.I MPID_Init

.PD 1
.PD 0
.TP
.B dmpi_recv_handle 
- API
.I 
s send handle
.PD 1

.SH SYNOPSIS
.nf
int MPID_Post_send_ready( void * ctx, MPIR_SHANDLE *dmpi_send_handle )
.fi

.SH NOTES
This routine only begins the send.  
.I MPID_Complete_send
 must be called
to finish the send, even if it was a blocking operation.  The matching
receive should already be posted.

It is legal to implement this with 
.I MPID_Post_send
.
