.TH MPID_HAS_HETERO 5 "10/10/1994" " " "ADI"
.SH NAME
MPID_HAS_HETERO \- Indicates that heterogeneous processors may be present

.SH NOTES
This is a macro that is defined when the ADI supports heterogeneous
processing elements.  APIs that are to operate in a heterogeneous
environment need to ensure that message are properly prepared.
See also ????? (heterogeneous support), MPID_IS_HETERO
