.TH MPID_IS_HETERO 5 "8/23/1995" " " "ADI"
.SH NAME
MPID_IS_HETERO \- Indicates that heterogeneous processors are present

.SH NOTES
This is a global variable that can be used to determine if an ADI
that could contain heterogeneous processors actually does.  For example,
if the ADI can connect disimilar workstations but the active collection
contains only similar workstations, then 
.I MPID_HAS_HETERO
 would be
defined, but 
.I MPID_IS_HETERO
 would be false.

See also the discussion on heterogeneous support.
