.TH MPID_RETURN_PACKED 5 "8/23/1995" " " "ADI"
.SH NAME
MPID_RETURN_PACKED \- Indicates that the ADI prefers to return a single
buffer

.SH NOTES
This is a macro that indicates that the data will be returned in the
data-area specified by the "start" field of the device handle.  If the
message is not contiguous, the API is responsible for unpacking the
message (with the routines MPIR_SetupUnPackMessage and MPIR_UnPackMessage)
