.TH MPID_PACK_IN_ADVANCE 5 "8/23/1995" " " "ADI"
.SH NAME
MPID_PACK_IN_ADVANCE \- Indicates that the ADI prefers to be given a single
buffer

.SH NOTES
This is a macro that indicates that the data will be provided in the
data-area specified by the "start" field of the device handle.  If the
message is not contiguous, the API is responsible for packing the
message (it may use 
.I MPIR_Pack
).

More advanced ADI implementations may inform the calling routines (the
API code) that the ADI can handle more complicated data, such as

.I MPID_DOES_STRIDED
.  The exact interface for this has not been
determined.
