.TH MPID_Version_name 5 "10/10/1994" " " "ADI"
.SH NAME
MPID_Version_name \- Provides a text string describing the version of the
ADI

.SH INPUT PARAMETER
.PD 0
.TP
.B ctx 
- ADI context returned by MPID_Init
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B name 
- Name of the version of the ADI.  Must be a string of at least
128 characters
.PD 1

.SH SYNOPSIS
.nf
void MPID_Version_name( void * ctx, char *name )
.fi

