#! /bin/sh
#
# Install script for the ch_p4mpd device
# This script is called by mpiinstall to install the device.
# It should add commands to the file named by UNINSTALLFILE to remove
# any file that it adds.
if [ -z "$MAKE" -o -z "$XMODE" ] ; then
    echo "This script must be invoked from mpiinstall"
    exit 1
fi
if [ -f mpid/mpd/Makefile ] ; then
    export XMODE
    (cd mpid/mpd ; $MAKE install UNINSTALLFILE=$UNINSTALLFILE )
else
    echo "Could not find Makefile for mpid/mpd!"
    echo "Install not completed"
    exit 1
fi
