#!/bin/sh
if [ -f coll.out ]; then
    /bin/rm -f coll.out.orig
    mv coll.out coll.out.orig
fi

#args=-mr_pg
echo '**** Testing MPI Collective routines ****'
echo '*** Collective Tests ***' > coll.out
echo '*** Barrier Test ***' >> coll.out
echo '**** Barrier Test ****'
mpirun $args barrier -mr_np 4 $* >> coll.out
cat barrier-0.out >> coll.out
echo '*** Barrier Test ***' >> coll.out
echo '**** Broadcast Test ****'
echo '*** Broadcast Test ***' >> coll.out
mpirun $args bcast -mr_np 4 $* >> coll.out
cat bcast-[0123].out >> coll.out
echo '*** Broadcast Test ***' >> coll.out
echo '**** coll1 ****'
echo '*** coll1 ***' >> coll.out
mpirun $args coll1 -mr_np 4 $* >> coll.out
echo '*** coll1 ***' >> coll.out
echo '**** coll2 ****'
echo '*** coll2 ***' >> coll.out
mpirun $args coll2 -mr_np 5 $* >> coll.out
echo '*** coll2 ***' >> coll.out
echo '**** coll3 ****'
echo '*** coll3 ***' >> coll.out
mpirun $args coll3 -mr_np 5 $* >> coll.out
echo '*** coll3 ***' >> coll.out
echo '**** coll4 ****'
echo '*** coll4 ***' >> coll.out
mpirun $args coll4 -mr_np 4 $* >> coll.out
echo '*** coll4 ***' >> coll.out
echo '**** coll5 ****'
echo '*** coll5 ***' >> coll.out
mpirun $args coll5 -mr_np 4 $* >> coll.out
echo '*** coll5 ***' >> coll.out
echo '**** coll6 ****'
echo '*** coll6 ***' >> coll.out
mpirun $args coll6 -mr_np 5 $* >> coll.out
echo '*** coll6 ***' >> coll.out
echo '**** coll7 ****'
echo '*** coll7 ***' >> coll.out
mpirun $args coll7 -mr_np 5 $* >> coll.out
echo '*** coll7 ***' >> coll.out
echo '**** coll8 ****'
echo '*** coll8 ***' >> coll.out
mpirun $args coll8 -mr_np 4 $* >> coll.out
echo '*** coll8 ***' >> coll.out
echo '**** coll9 ****'
echo '*** coll9 ***' >> coll.out
mpirun $args coll9 -mr_np 4 $* >>  coll.out
echo '*** coll9 ***' >> coll.out
echo '**** coll10 ****'
echo '*** coll10 ***' >> coll.out
mpirun coll10 $args -mr_np 4 $* >> coll.out
echo '*** coll10 ***' >> coll.out
echo '**** coll11 ****'
echo '*** coll11 ***' >> coll.out
mpirun coll11 $args -mr_np 4 $* >> coll.out
echo '*** coll11 ***' >> coll.out
echo '**** coll12 ****'
echo '*** coll12 ***' >> coll.out
mpirun $args coll12 $args -mr_np 4 $* >> coll.out
echo '*** coll12 ***' >> coll.out
echo '*** Grouptest ***'
echo '*** grouptest ***' >> coll.out
mpirun $args grouptest -mr_np 4 $* >> coll.out
echo '*** grouptest ***' >> coll.out
echo '*** Differences from expected output ***'
diff -b coll.out coll.std
exit 0
