#
#  $Id: makefile,v 1.2 1993/11/12 12:11:46 doss Exp $
#
#  (C) 1993 by Argonne National Laboratory and Mississipi State University.
#      All rights reserved.  See COPYRIGHT in top-level directory.
#

DEVICE_INCLUDE = ../../mpid/$(DEVICE)/dmch.h

MPI_INCLUDE    = ../../include/mpi.h ../../include/mpi_bc.h \
                 ../../include/mpir.h ../../include/mpi_ad.h \
		 ../../include/mpisys.h 
DEVICE_LIB = 
CFLAGS = -g -I../../include -I../../mpid/$(DEVICE) $(OTHERINCDIR)
CC = cc
AR = ar
RANLIB = ranlib
LIBS = ../../lib/$(ARCH)/libmpi.a $(DEVICE_LIB)
MPI_SOURCES =  util_hbt.c mpirutil.c sbcnst.c util_hbt.c
MPI_OBJECTS =  util_hbt.o mpirutil.o sbcnst.o util_hbt.o

default: ../../lib/$(ARCH)/libmpi.a

$(MPI_OBJECTS) :  $(MPI_INCLUDE)

.c.o:
	$(CC) $(CFLAGS) -c $*.c

../../lib/$(ARCH)/libmpi.a: $(MPI_OBJECTS) 
	$(AR) crl $@ $?
	$(RANLIB) $@

clean:
	/bin/rm -f *.o *~ ../../lib/libmpi.a
