P4_HOME_DIR = ..
INCLUDEDIR = $(P4_HOME_DIR)/include
LIBDIR = $(P4_HOME_DIR)/lib
LIBS = $(MDEP_LIBS)

USC_HDR = usc_sys.h usc.h
USC_SRC = usc.c
USC_OBJ = usc.o

default:	
	make $(LIBDIR)/libp4.a

all:	
	make $(LIBDIR)/libp4.a

USER_CFLAGS = -D$(P4ARCH)

usc.o:$(P)
	$(CC) $(CFLAGS) -I$(INCLUDEDIR) -c usc.c 

$(USC_OBJ):  $(USC_SRC) $(USC_HDR)


$(LIBDIR)/libp4.a:  $(USC_OBJ)
	$(AR) $(LIBDIR)/libp4.a $?
	$(RANLIB) $(LIBDIR)/libp4.a
#	$(AR) $@ $?
#	$(RANLIB) $@

p4inmpi:$(P) $(USC_OBJ)
	$(AR) ../../../../lib/$(MPIARCH)/ch_p4/libmpi.a $?
	$(RANLIB) ../../../../lib/$(MPIARCH)/ch_p4/libmpi.a

realclean:	clean
	$(RM) -f $(LIBDIR)/libp4.a Makefile
	@cd usctest; make clean

