#! /bin/sh
#
# Run some of the tests.  If any arguments are provided, pass them to the
# test programs.
#
# -mvhome is needed for the ANL SP, and is ignored by others
args="-pg -mvhome"
#
# Some people don't include "." in their path (! in case an ls trojan horse,
# I guess - if someone does that to you, you have bigger problems).  This
# code tests to see if you have a path to mpirun; if not, it tries ./mpirun.
IFS="${IFS= 	}"; saveifs="$IFS"; IFS="${IFS}:"
for dir in $PATH ; do 
    if [ -x $dir/mpirun ] ; then
        mpirun="mpirun"
        break
    fi
done
IFS="$saveifs"
if [ -z "$mpirun" -a -x "./mpirun" ] ; then
    mpirun=./mpirun
fi
if [ -z "$mpirun" ] ; then
    echo "No mpirun in path.  Testing can not proceed."
    exit 1
fi
#
runtests=1
makeeach=0
MAKE="make"
for arg in "$@" ; do
    case $arg in 
	-checkonly )
	runtests=0
	;;
        -margs=*)
	margs=`echo $arg | sed 's/-margs=//'`
	args="$args $margs"
	;;
	-small)
	makeeach=1
	;;
	-help|-u)
	echo "runtests [-checkonly] [-margs='...']"
	echo "run tests in this directory.  If -checkonly set, just run"
	echo "the differences check (do NO rerun the test programs)."
	echo "If -margs is used, these options are passed to mpirun."
	echo "If -small is used, the examples are built, run, and deleted."
	exit 1
	;;
	*)
	if test -n "$arg" ; then
   	    echo "runtests: Unknown argument ($arg)"
	    exit 1
        fi
	;;
    esac
done

MakeExe() {
    if [ ! -x $1 ] ; then
	$MAKE $1
    fi
}
CleanExe() {
    if [ $makeeach = 1 ] ; then
	/bin/rm -f $1 $1.o
    fi
}
# If the programs are not available, run make.
if [ ! -x sigchk -a $makeeach = 0 ] ; then
    $MAKE default
fi
#
testfiles=""
if [ $runtests = 1 ] ; then

testfiles="$testfiles timers.out"
/bin/rm -f timers.out
MakeExe timers
echo "*** Timer tests ***"
echo "*** Timer tests ***" >> timers.out
$mpirun $args -np 1 timers $* >> timers.out
echo "*** Timer tests ***" >> timers.out
CleanExe timers

testfiles="$testfiles init.out"
/bin/rm -f init.out
MakeExe init
echo "*** MPI_Initialized tests ***"
echo "*** MPI_Initialized tests ***" >> init.out
$mpirun $args -np 2 ./init $* >> init.out
echo "*** MPI_Initialized tests ***" >> init.out
CleanExe init

testfiles="$testfiles baseattr.out"
/bin/rm -f baseattr.out
MakeExe baseattr
echo "*** Basic attributes ***"
echo "*** Basic attributes ***" >> baseattr.out
$mpirun $args -np 1 baseattr $* >> baseattr.out
echo "*** Basic attributes ***" >> baseattr.out
CleanExe baseattr

testfiles="$testfiles errhand.out"
/bin/rm -f errhand.out
MakeExe errhand
echo "*** Tests of error handling ***" 
echo "*** Tests of error handling ***" >>errhand.out
$mpirun $args -np 1 errhand $* >> errhand.out
echo "*** Tests of error handling ***" >>errhand.out
CleanExe errhand

testfiles="$testfiles sigchk.out"
/bin/rm -f sigchk.out
MakeExe sigchk
echo "*** Tests of signals used ***"
echo "*** Tests of signals used ***" >> sigchk.out
$mpirun $args -np 1 sigchk $* >> sigchk.out
echo "*** Tests of signals used ***" >> sigchk.out
CleanExe sigchk

else
    # Just run checks
    testfiles=*.out
    if test "$testfiles" eq "*.out" ; then
	echo "No output files remain from previous test!"
	exit 1
    fi
fi

#
echo '*** Checking for differences from expected output ***'
/bin/rm -f env.diff
nodiff=1
for file in $testfiles ; do
    stdfile=`basename $file .out`.std
    if [ -s $stdfile ] ; then
        if diff -b $file `basename $file .out`.std > /dev/null ; then
	    true
        else
	    echo "Differences in `basename $file .out`" >> env.diff
	    diff -b $file `basename $file .out`.std >> env.diff
	    nodiff=0
	fi
    else
        echo "Can not find file $stdfile to compare against for test `basename $file .out`"
    fi
done
if [ -s env.diff ] ; then
   cat env.diff
elif [ $nodiff = 1 ] ; then
   echo "-- No differences found; test successful"
fi
exit 0
