
NEXUS_DIR=/usr/local/nexus-4.0b1/solaris_dl

include $(NEXUS_DIR)/makefile_header

MY_CFLAGS = -I$(includedir) $(ALL_CFLAGS)
MY_LDFLAGS = -L$(libdir) -lnexus$(nexus_flavor) $(ALL_LDFLAGS) $(ALL_LIBS)

test_nx:	test_nx.o
	$(CC) $(MY_CFLAGS) -o test_nx test_nx.o $(MY_LDFLAGS)

test_nx.o:	test_nx.c
	$(CC) $(MY_CFLAGS) -c test_nx.c

clean:
	rm -f *.o test_nx

