#
#  $Id: makefile,v 1.5 1993/11/24 00:47:43 doss Exp $
#
#  (C) 1993 by Argonne National Laboratory and Mississipi State University.
#      All rights reserved.  See COPYRIGHT in top-level directory.
#

DEVICE_INCLUDE = ../../mpid/$(DEVICE)/dmch.h

MPI_INCLUDE    = ../../include/mpi.h ../../include/mpi_bc.h \
                 ../../include/mpir.h ../../include/mpi_ad.h \
		 ../../include/mpisys.h 
DEVICE_LIB = 
CFLAGS = -g -I../../include -I../../mpid/$(DEVICE) $(OTHERINCDIR)
CC = cc
AR = ar
RANLIB = ranlib
LIBS = ../../lib/$(ARCH)/libmpi.a $(DEVICE_LIB)
MPI_SOURCES = global.c isend.c irecv.c wait.c test.c mperror.c \
              address.c cancel.c commreq_free.c comm_init.c probe.c \
              start.c testany.c datatypes.c waitall.c send.c recv.c \
	      recvf.c sendf.c sendrecv.c
MPI_OBJECTS = global.o isend.o irecv.o wait.o test.o mperror.o \
              address.o cancel.o commreq_free.o comm_init.o probe.o \
              start.o testany.o datatypes.o waitall.o send.o recv.o \
	      recvf.o sendf.o sendrecv.o

default: ../../lib/$(ARCH)/libmpi.a

$(MPI_OBJECTS) :  $(MPI_INCLUDE)

.c.o:
	$(CC) $(CFLAGS) -c $*.c

../../lib/$(ARCH)/libmpi.a: $(MPI_OBJECTS) 
	$(AR) crl $@ $?
	$(RANLIB) $@

clean:
	/bin/rm -f *.o *~ ../../lib/libmpi.a
