#! /bin/sh
#
# Make a tar file of the MPE code, removing the RCS files etc.
#
set -x
#
# Use tar to copy to /tmp
if [ ! -d /tmp/mpecopy ] ; then
    mkdir /tmp/mpecopy
fi
cd /tmp/mpecopy
tar cf - -C /home/MPI/mpich mpe | tar xf -
#
# Update a few files
rm /tmp/mpecopy/mpe/requests.h
cp /home/MPI/mpich/profiling/lib/requests.h /tmp/mpecopy/mpe
rm /tmp/mpecopy/mpe/point.h
cp /home/MPI/mpich/profiling/lib/point.h /tmp/mpecopy/mpe
cp /home/MPI/mpich/include/mpiprof.h /tmp/mpecopy/mpe
cp /home/MPI/mpich/util/tarch /tmp/mpecopy/mpe
#
# Copy the man pages
mkdir /tmp/mpecopy/mpe/man
cp -rp /home/MPI/mpich/man/man4 /tmp/mpecopy/mpe/man/man4
mkdir /tmp/mpecopy/mpe/www
cp -rp /home/MPI/mpich/www/www4 /tmp/mpecopy/mpe/www/www4
#
rm /tmp/mpecopy/mpe/aclocal.m4
cp /home/MPI/mpich/aclocal.m4 /tmp/mpecopy/mpe
# The next copy pulls in versions of mpicc and mpirun that may
# be useful.
cp -rp /home/MPI/class/mpiexmpl/maint/envs /tmp/mpecopy/bin
chmod a+x /tmp/mpecopy/mpe/tarch
#
# Remove the RCS files, old executables, and debris
cd /tmp/mpecopy/mpe
find . \( -name 'RCS' -o -name '*.o' -o -name '#*#' -o \
              -name '*~' -o -name 'mputil.mp*' -o -name Makefile -o \
	      -name makefile -o -name 'PI*' -o -name 'mpirun' -o \
	      -name 'mpif.h' \) -print | \
	sed 's%^%/bin/rm -rf %g' | sh
#
# rebuild the tar file
cd /tmp/mpecopy
tar cf - mpe | gzip > /tmp/mpe.tar.gz
/bin/rm -rf /tmp/mpecopy &
echo "tar file in /tmp/mpe.tar.gz"
