.TH MPI_Cartdim_get 3 "12/15/1994" " " "MPI"
.SH NAME
MPI_Cartdim_get \- Retrieves Cartesian topology information associated with a
communicator

.SH INPUT PARAMETER
.PD 0
.TP
.B comm 
- communicator with cartesian structure (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B ndims 
- number of dimensions of the cartesian structure (integer) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Cartdim_get ( comm, ndims )
MPI_Comm  comm;
int      *ndims;

.fi

.SH LOCATION
 cartdim_get.c
