.TH MPI_Bcast 3 "9/21/1994" " " "MPI"
.SH NAME
MPI_Bcast \- Broadcasts a message from the process with rank "root" to
all other processes of the group.

.SH INPUT/OUTPUT PARAMETER
.PD 0
.TP
.B buffer 
- starting address of buffer (choice) 
.PD 1
.PD 0
.TP
.B count 
- number of entries in buffer (integer) 
.PD 1
.PD 0
.TP
.B datatype 
- data type of buffer (handle) 
.PD 1
.PD 0
.TP
.B root 
- rank of broadcast root (integer) 
.PD 1
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH ALGORITHM
This function uses a tree-like algorithm to broadcast
the message to blocks of processes.  A linear algorithm
is then used to broadcast the message from the first
process in a block to all other processes.
MPIR_BCAST_BLOCK_SIZE determines the size of blocks.  If
this is set to 1, then this function is equivalent to
using a pure tree algorithm.  If it is set to the
size of the group or greater, it is a pure linear algorithm.
The value should be adjusted to determine the most
efficient value on different machines.

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Bcast ( buffer, count, datatype, root, comm )
void             *buffer;
int               count;
MPI_Datatype      datatype;
int               root;
MPI_Comm          comm;

.fi

.SH LOCATION
 bcast.c
