.TH MPI_Op_create 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Op_create \- Creates a user-defined combination function handle

.SH INPUT PARAMETERS
.PD 0
.TP
.B function 
- user defined function (function) 
.PD 1
.PD 0
.TP
.B commute 
-  true if commutative;  false otherwise. 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B op 
- operation (handle) 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Op_create( function, commute, op )
MPI_User_function *function;
int               commute;
MPI_Op            *op;

.fi

.SH LOCATION
 opcreate.c
