.TH MPI_Testall 3 "1/3/1995" " " "MPI"
.SH NAME
MPI_Testall \- Tests for the completion of all previously initiated
communications

.SH INPUT PARAMETERS
.PD 0
.TP
.B count 
- lists length (integer) 
.PD 1
.PD 0
.TP
.B array_of_requests 
- array of requests (array of handles) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B flag 
- (logical) 
.PD 1
.PD 0
.TP
.B array_of_statuses 
- array of status objects (array of Status) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Testall( count, array_of_requests, flag, array_of_statuses )
int        count;
MPI_Request array_of_requests[];
int        *flag;
MPI_Status *array_of_statuses;

.fi

.SH LOCATION
 testall.c
