.TH MPI_Test_cancelled 3 "7/13/1994" " " "MPI"
.SH NAME
MPI_Test_cancelled \- Tests to see if a request was canceled

.SH INPUT PARAMETER
.PD 0
.TP
.B status 
- status object (Status) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B flag 
- (logical) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Test_cancelled( status, flag )
MPI_Status *status;
int        *flag;

.fi

.SH LOCATION
 testcancel.c
