.TH MPI_Errhandler_get 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Errhandler_get \- Gets the error handler for a communicator

.SH INPUT PARAMETER
.PD 0
.TP
.B comm 
- communicator to get the error handler from (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B errhandler 
- MPI error handler currently associated with communicator
(handle) 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Errhandler_get( comm, errhandler )
MPI_Comm comm;
MPI_Errhandler *errhandler;

.fi

.SH LOCATION
 errget.c
