.TH MPI_Attr_put 3 "8/12/1994" " " "MPI"
.SH NAME
MPI_Attr_put \- Stores attribute value associated with a key

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator to which attribute will be attached (handle) 
.PD 1
.PD 0
.TP
.B keyval 
- key value, as returned by  MPI_KEYVAL_CREATE (integer) 
.PD 1
.PD 0
.TP
.B attribute_val 
- attribute value 
.PD 1

.SH NOTES
Values of the permanent attributes MPI_TAG_UB, MPI_HOST, and MPI_IO may not
be changed.

The type of the attribute value depends on whether C or Fortran is being used.
In C, an attribute value is a pointer (void *); in Fortran, it is a single
integer (NOT a pointer, since Fortran has no pointers and their are systems
for which a pointer does not fit in an integer (e.g., any > 32 bit address
system that uses 64 bits for Fortran DOUBLE PRECISION).
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Attr_put ( comm, keyval, attr_value )
MPI_Comm comm;
int      keyval;
void     *attr_value;

.fi

.SH LOCATION
 attr_putval.c
