.TH MPI_Comm_remote_size 3 "7/13/1994" " " "MPI"
.SH NAME
MPI_Comm_remote_size \- Determines the size of the remote group
associated with an inter-communictor

.SH INPUT PARAMETER
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B size 
- number of processes in the group of comm  (integer) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Comm_remote_size ( comm, size )
MPI_Comm  comm;
int      *size;

.fi

.SH LOCATION
 comm_rsize.c
