.TH MPI_Cart_shift 3 "5/9/1995" " " "MPI"
.SH NAME
MPI_Cart_shift \- Returns the shifted source and destination ranks, given a
shift direction and amount

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator with cartesian structure (handle) 
.PD 1
.PD 0
.TP
.B direction 
- coordinate dimension of shift (integer) 
.PD 1
.PD 0
.TP
.B disp 
- displacement ($> 0$: upwards shift, $< 0$: downwards shift) (integer) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B rank_source 
- rank of source process (integer) 
.PD 1
.PD 0
.TP
.B rank_dest 
- rank of destination process (integer) 
.PD 1

.SH NOTES
The 'direction' argument is in the range [0,n-1] for an n-dimensional
Cartesian mesh.

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Cart_shift ( comm, direction, displ, source, dest )
MPI_Comm  comm;
int       direction;
int       displ;
int      *source;
int      *dest;

.fi

.SH LOCATION
 cart_shift.c
