.TH MPI_Waitsome 3 "3/5/1995" " " "MPI"
.SH NAME
MPI_Waitsome \- Waits for some given communications to complete

.SH INPUT PARAMETERS
.PD 0
.TP
.B incount 
- length of array_of_requests (integer) 
.PD 1
.PD 0
.TP
.B array_of_requests 
- array of requests (array of handles) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B outcount 
- number of completed requests (integer) 
.PD 1
.PD 0
.TP
.B array_of_indices 
- array of indices of operations that 
completed (array of integers) 
.PD 1
.PD 0
.TP
.B array_of_statuses 
- array of status objects for 
operations that completed (array of Status) 
.PD 1

.SH NOTES
The array of indicies are in the range 0 to incount - 1 for C and
in the range 1 to incount for Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Waitsome( incount, array_of_requests, outcount, array_of_indices, 
    array_of_statuses )
int         incount, *outcount, array_of_indices[];
MPI_Request array_of_requests[];
MPI_Status  array_of_statuses[];

.fi

.SH LOCATION
 waitsome.c
