.TH MPI_Graphdims_get 3 "4/23/1995" " " "MPI"
.SH NAME
MPI_Graphdims_get \- Retrieves graph topology information associated with a
communicator

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator for group with graph structure (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B nnodes 
- number of nodes in graph (integer) 
.PD 1
.PD 0
.TP
.B nedges 
- number of edges in graph (integer) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Graphdims_get ( comm, nnodes, nedges )
MPI_Comm  comm;
int              *nnodes;
int              *nedges;

.fi

.SH LOCATION
 graphdimsget.c
