.TH MPI_Barrier 3 "6/20/1995" " " "MPI"
.SH NAME
MPI_Barrier \- Blocks until all process have reached this routine.

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH NOTES
Blocks the caller until all group members have called it;
the call returns at any process only after all group members
have entered the call.

.SH ALGORITHM
If the underlying device cannot do better, a tree-like or combine
algorithm is used to broadcast a message wto all members of the
communicator.  We can modifiy this to use "blocks" at a later time
(see MPI_Bcast).

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Barrier ( comm )
MPI_Comm comm;

.fi

.SH LOCATION
 barrier.c
