.TH MPI_Comm_compare 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Comm_compare \- Compares two communicators

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm1 
- comm1 (handle) 
.PD 1
.PD 0
.TP
.B comm2 
- comm2 (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B result 
- integer which is 
.I MPI_IDENT
if the contexts and groups are the
same, 
.I MPI_CONGRUENT
if different contexts but identical groups, 
.I MPI_SIMILAR
if different contexts but similar groups, and 
.I MPI_UNEQUAL
otherwise
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Comm_compare ( comm1, comm2, result )
MPI_Comm  comm1;
MPI_Comm  comm2;
int       *result;

.fi

.SH LOCATION
 commcompare.c
