.TH MPI_Comm_test_inter 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Comm_test_inter \- Tests to see if a comm is an inter-communicator

.SH INPUT PARAMETER
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B flag 
- (logical) 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Comm_test_inter ( comm, flag )
MPI_Comm  comm;
int      *flag;

.fi

.SH LOCATION
 comm_testic.c
