.TH MPI_Cart_sub 3 "7/24/1995" " " "MPI"
.SH NAME
MPI_Cart_sub \- Partitions a communicator into subgroups which
form lower-dimensional cartesian subgrids

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator with cartesian structure (handle) 
.PD 1
.PD 0
.TP
.B remain_dims 
- the  i th entry of remain_dims specifies whether the i th 
dimension is kept in the subgrid ( true ) or is dropped ( false ) (logical 
vector) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B newcomm 
- communicator containing the subgrid that includes the calling 
process (handle) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Cart_sub ( comm, remain_dims, comm_new )
MPI_Comm  comm;
int      *remain_dims;
MPI_Comm *comm_new;

.fi

.SH LOCATION
 cart_sub.c
