.TH MPI_Handle2int 3 "2/19/1997" " " "MPI"
.SH NAME
MPI_Handle2int \-  Convert a C handle to an integer (Fortran) MPI handle 
.SH SYNOPSIS
.nf
#include "mpi.h"
MPI_Fint MPI_Handle2int( c_handle, handle_kind )
MPI_Handle_type c_handle;
MPI_Handle_enum handle_kind;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B c_handle 
- C handle
.PD 1
.PD 0
.TP
.B handle_kind 
- Type of handle 
.PD 1

.SH RETURN VALUE
.PD 0
.TP
.B f_handle 
- Fortran version of handle.
.PD 1

.SH NOTES FOR FORTRAN USERS
There is no Fortran version of this routine.

.SH NOTE ON STANDARD
This function is part of the MPI-2 draft, and may change while the draft
undergoes revision.  It is provided as an aid to programmers who wish
to experiment with some MPI2 features.
.SH LOCATION
handle2int.c
