.TH MPI_Keyval_create 3 "4/23/1995" " " "MPI"
.SH NAME
MPI_Keyval_create \- Generates a new attribute key

.SH INPUT PARAMETERS
.PD 0
.TP
.B copy_fn 
- Copy callback function for keyval 
.PD 1
.PD 0
.TP
.B delete_fn 
- Delete callback function for keyval 
.PD 1
.PD 0
.TP
.B extra_state 
- Extra state for callback functions 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B keyval 
- key value for future access (integer) 
.PD 1

.SH NOTES
Key values are global (available for any and all communicators).

There are subtle differences between C and Fortran that require that the
copy_fn be written in the same language that MPI_Keyval_create is called from.
This should not be a problem for most users; only programers using both
Fortran and C in the same program need to be sure that they follow this rule.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Keyval_create ( copy_fn, delete_fn, keyval, extra_state )
MPI_Copy_function   *copy_fn;
MPI_Delete_function *delete_fn;
int                 *keyval;
void                *extra_state;

.fi

.SH LOCATION
 keyvalcreate.c
