.TH MPI_Group_union 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Group_union \- Produces a group by combining two groups

.SH INPUT PARAMETERS
.PD 0
.TP
.B group1 
- first group (handle) 
.PD 1
.PD 0
.TP
.B group2 
- second group (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B newgroup 
- union group (handle) 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Group_union ( group1, group2, group_out )
MPI_Group group1, group2, *group_out;

.fi

.SH LOCATION
 group_union.c
