.TH MPI_Type_size 3 "12/15/1994" " " "MPI"
.SH NAME
MPI_Type_size \- Return the number of bytes occupied by entries
in the datatype

.SH INPUT PARAMETERS
.PD 0
.TP
.B datatype 
- datatype (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B size 
- datatype size (integer) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Type_size ( datatype, size )
MPI_Datatype  datatype;
MPI_Aint     *size;

.fi

.SH LOCATION
 type_size.c
