.TH MPI_Intercomm_merge 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Intercomm_merge \- Creates an intracommuncator from an intercommunicator

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- Intercommunicator
.PD 1
.PD 0
.TP
.B high 
- Used to order the groups of the two intracommunicators within comm
when creating the new communicator.  
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B comm_out 
- Created intracommunicator
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.

.SH ALGORITHM
.PD 0
.TP
.B 1) 
Allocate two contexts 
.PD 1
.PD 0
.TP
.B 2) 
Local and remote group leaders swap high values
.PD 1
.PD 0
.TP
.B 3) 
Determine the high value.
.PD 1
.PD 0
.TP
.B 4) 
Merge the two groups and make the intra-communicator
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Intercomm_merge ( comm, high, comm_out )
MPI_Comm  comm;
int       high;
MPI_Comm *comm_out;

.fi

.SH LOCATION
 ic_merge.c
