.TH MPI_Bsend_init 3 "5/9/1995" " " "MPI"
.SH NAME
MPI_Bsend_init \- Builds a handle for a buffered send

.SH INPUT PARAMETERS
.PD 0
.TP
.B buf 
- initial address of send buffer (choice) 
.PD 1
.PD 0
.TP
.B count 
- number of elements sent (integer) 
.PD 1
.PD 0
.TP
.B datatype 
- type of each element (handle) 
.PD 1
.PD 0
.TP
.B dest 
- rank of destination (integer) 
.PD 1
.PD 0
.TP
.B tag 
- message tag (integer) 
.PD 1
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B request 
- communication request (handle) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Bsend_init( buf, count, datatype, dest, tag, comm, request )
void          *buf;
int           count;
MPI_Datatype  datatype;
int           dest;
int           tag;
MPI_Comm      comm;
MPI_Request   *request;

.fi

.SH LOCATION
 bsend_init.c
