.TH MPI_Graph_map 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Graph_map \- Maps process to graph topology information

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- input communicator (handle) 
.PD 1
.PD 0
.TP
.B nnodes 
- number of graph nodes (integer) 
.PD 1
.PD 0
.TP
.B index 
- integer array specifying the graph structure, see 
.I MPI_GRAPH_CREATE
.PD 1
.PD 0
.TP
.B edges 
- integer array specifying the graph structure 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B newrank 
- reordered rank of the calling process; 
.I MPI_UNDEFINED
if the 
calling process does not belong to graph (integer) 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Graph_map ( comm_old, nnodes, index, edges, newrank )
MPI_Comm comm_old;
int      nnodes;
int     *index;
int     *edges;
int     *newrank;

.fi

.SH LOCATION
 graph_map.c
