.TH MPI_Buffer_attach 3 "5/9/1995" " " "MPI"
.SH NAME
MPI_Buffer_attach \- Attaches a user-defined buffer for sending

.SH INPUT PARAMETERS
.PD 0
.TP
.B buffer 
- initial buffer address (choice) 
.PD 1
.PD 0
.TP
.B size 
- buffer size, in bytes (integer) 
.PD 1

.SH NOTES
The size given should be the sum of the sizes of all outstanding Bsends that
you intend to have, plus a few hundred bytes for each Bsend that you do.
For the purposes of calculating size, you should use MPI_Pack_size.
In other words, in the code
.nf
     MPI_Buffer_attach( buffer, size );
     MPI_Bsend( ..., count=20, datatype=type1,  ... );
     ...
     MPI_Bsend( ..., count=40, datatype=type2, ... );
.fi

the value of 'size' in the MPI_Buffer_attach call should be greater than
the value computed by
.nf
     MPI_Pack_size( 20, type1, comm, &s1 );
     MPI_Pack_size( 40, type2, comm, &s2 );
     size = s1 + s2 + 2 * MPI_BSEND_OVERHEAD;
.fi

The MPI_BSEND_OVERHEAD gives the maximum amount of space that may be used in
the buffer for use by the BSEND routines in using the buffer.  This value
is in 'mpi.h' (for C) and 'mpif.h' (for Fortran).

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Buffer_attach( buffer, size )
void *buffer;
int  size;

.fi

.SH LOCATION
 bufattach.c
