.TH MPI_Wait 3 "12/15/1994" " " "MPI"
.SH NAME
MPI_Wait - Waits for an MPI send or receive to complete

.SH INPUT PARAMETER
.PD 0
.TP
.B request 
- request (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B status 
- status object (Status) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Wait ( request, status )
MPI_Request  *request;
MPI_Status   *status;

.fi

.SH LOCATION
 wait.c
