.TH MPI_Testany 3 "1/14/1995" " " "MPI"
.SH NAME
MPI_Testany \- Tests for completion of any previdously initiated
communication

.SH INPUT PARAMETERS
.PD 0
.TP
.B count 
- list length (integer) 
.PD 1
.PD 0
.TP
.B array_of_requests 
- array of requests (array of handles) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B index 
- index of operation that completed, or MPI_UNDEFINED  if none 
completed (integer) 
.PD 1
.PD 0
.TP
.B flag 
- true if one of the operations is complete (logical) 
.PD 1
.PD 0
.TP
.B status 
- status object (Status) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Testany( count, array_of_requests, index, flag, status )
int         count;
MPI_Request array_of_requests[];
int         *index, *flag;
MPI_Status  *status;

.fi

.SH LOCATION
 testany.c
