.TH MPI_Graph_create 3 "9/30/1994" " " "MPI"
.SH NAME
MPI_Graph_create \- Makes a new communicator to which topology information
has been attached

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm_old 
- input communicator without topology (handle) 
.PD 1
.PD 0
.TP
.B nnodes 
- number of nodes in graph (integer) 
.PD 1
.PD 0
.TP
.B index 
- array of integers describing node degrees (see below) 
.PD 1
.PD 0
.TP
.B edges 
- array of integers describing graph edges (see below) 
.PD 1
.PD 0
.TP
.B reorder 
- ranking may be reordered (true ) or not (false ) (logical) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B comm_graph 
- communicator with graph topology added (handle) 
.PD 1

.SH ALGORITHM
We ignore the periods and reorder info currently.

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Graph_create ( comm_old, nnodes, index, edges, reorder, comm_graph )
MPI_Comm  comm_old;
int       nnodes;
int      *index;
int      *edges;
int       reorder;
MPI_Comm *comm_graph;

.fi

.SH LOCATION
 graph_create.c
