.TH MPI_Testsome 3 "1/3/1995" " " "MPI"
.SH NAME
MPI_Testsome \- Tests for some given communications to complete

.SH INPUT PARAMETERS
.PD 0
.TP
.B incount 
- length of array_of_requests (integer) 
.PD 1
.PD 0
.TP
.B array_of_requests 
- array of requests (array of handles) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B outcount 
- number of completed requests (integer) 
.PD 1
.PD 0
.TP
.B array_of_indices 
- array of indices of operations that 
completed (array of integers) 
.PD 1
.PD 0
.TP
.B array_of_statuses 
- array of status objects for 
operations that completed (array of Status) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Testsome( incount, array_of_requests, outcount, array_of_indices, 
    array_of_statuses )
int         incount, *outcount, array_of_indices[];
MPI_Request array_of_requests[];
MPI_Status  array_of_statuses[];

.fi

.SH LOCATION
 testsome.c
