.TH MPI_NULL_DELETE_FN 3 "1/8/1996" " " "MPI"
.SH NAME
MPI_NULL_DELETE_FN \- A function to not delete attributes

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- Communicator
.PD 1
.PD 0
.TP
.B keyval 
- Key value
.PD 1
.PD 0
.TP
.B attr 
- attribute
.PD 1
.PD 0
.TP
.B extra_state 
- User-defined state to give user functions
.PD 1

.SH NOTES
See discussion of MPI_Keyval_create for the use of this function.


.SH LOCATION
 null_del_fn.c
