.TH MPI_Recv 3 "5/16/1995" " " "MPI"
.SH NAME
MPI_Recv \- Basic receive

.SH OUTPUT PARAMETER
.PD 0
.TP
.B buf 
- initial address of receive buffer (choice) 
.PD 1
.PD 0
.TP
.B status 
- status object (Status) 
.PD 1

.SH INPUT PARAMETERS
.PD 0
.TP
.B count 
- number of elements in receive buffer (integer) 
.PD 1
.PD 0
.TP
.B datatype 
- datatype of each receive buffer element (handle) 
.PD 1
.PD 0
.TP
.B source 
- rank of source (integer) 
.PD 1
.PD 0
.TP
.B tag 
- message tag (integer) 
.PD 1
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Recv( buf, count, datatype, source, tag, comm, status )
void             *buf;
int              count, source, tag;
MPI_Datatype     datatype;
MPI_Comm         comm;
MPI_Status       *status;

.fi

.SH LOCATION
 recv.c
