.TH MPI_Error_string 3 "11/8/1994" " " "MPI"
.SH NAME
MPI_Error_string \- Return a string for a given error code

.SH INPUT PARAMETERS
.PD 0
.TP
.B errorcode 
- Error code returned by an MPI routine 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B string 
- Text that corresponds to the errorcode 
.PD 1
.PD 0
.TP
.B resultlen 
- Length of string 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Error_string( errorcode, string, resultlen )
int  errorcode, *resultlen;
char *string;

.fi

.SH LOCATION
 error_string.c
