.TH MPI_DUP_FN 3 "1/8/1996" " " "MPI"
.SH NAME
MPI_DUP_FN \- A function to simple-mindedly copy attributes

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPIR_dup_fn ( comm, keyval, extra_state, attr_in, attr_out, flag )
MPI_Comm  comm;
int       keyval;
void      *extra_state;
void      *attr_in;
void      *attr_out;
int       *flag;

.fi

.SH LOCATION
 dup_fn.c
