.TH MPI_Group_translate_ranks 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Group_translate_ranks \- Translates the ranks of processes in one group to
those in another group

.SH INPUT PARAMETERS
.PD 0
.TP
.B group1 
- group1 (handle) 
.PD 1
.PD 0
.TP
.B n 
- number of ranks in  
.I ranks1
and 
.I ranks2
arrays (integer) 
.PD 1
.PD 0
.TP
.B ranks1 
- array of zero or more valid ranks in 
.I group1
.PD 1
.PD 0
.TP
.B group2 
- group2 (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B ranks2 
- array of corresponding ranks in group2,  
.I MPI_UNDEFINED
when no 
correspondence exists. 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Group_translate_ranks ( group_a, n, ranks_a, group_b, ranks_b )
MPI_Group group_a;
int n;
int       *ranks_a;
MPI_Group  group_b;
int       *ranks_b;

.fi

.SH LOCATION
 group_tranks.c
