.TH MPI_Sendrecv 3 "1/12/1996" " " "MPI"
.SH NAME
MPI_Sendrecv \- Sends and receives a message

.SH INPUT PARAMETERS
.PD 0
.TP
.B sendbuf 
- initial address of send buffer (choice) 
.PD 1
.PD 0
.TP
.B sendcount 
- number of elements in send buffer (integer) 
.PD 1
.PD 0
.TP
.B sendtype 
- type of elements in send buffer (handle) 
.PD 1
.PD 0
.TP
.B dest 
- rank of destination (integer) 
.PD 1
.PD 0
.TP
.B sendtag 
- send tag (integer) 
.PD 1
.PD 0
.TP
.B recvcount 
- number of elements in receive buffer (integer) 
.PD 1
.PD 0
.TP
.B recvtype 
- type of elements in receive buffer (handle) 
.PD 1
.PD 0
.TP
.B source 
- rank of source (integer) 
.PD 1
.PD 0
.TP
.B recvtag 
- receive tag (integer) 
.PD 1
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B recvbuf 
- initial address of receive buffer (choice) 
.PD 1
.PD 0
.TP
.B status 
- status object (Status).  This refers to the receive operation.
.PD 1


.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Sendrecv( sendbuf, sendcount, sendtype, dest, sendtag, 
                  recvbuf, recvcount, recvtype, source, recvtag, 
                  comm, status )
void         *sendbuf;
int           sendcount;
MPI_Datatype  sendtype;
int           dest, sendtag;
void         *recvbuf;
int           recvcount;
MPI_Datatype  recvtype;
int           source, recvtag;
MPI_Comm      comm;
MPI_Status   *status;

.fi

.SH LOCATION
 sendrecv.c
