.TH MPI_Cart_get 3 "12/21/1995" " " "MPI"
.SH NAME
MPI_Cart_get \- Retrieves Cartesian topology information associated with a
communicator

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator with cartesian structure (handle) 
.PD 1
.PD 0
.TP
.B maxdims 
- length of vectors  
.I dims
, 
.I periods
, and 
.I coords
in the calling program (integer) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B dims 
- number of processes for each cartesian dimension (array of integer) 
.PD 1
.PD 0
.TP
.B periods 
- periodicity (true/false) for each cartesian dimension 
(array of logical) 
.PD 1
.PD 0
.TP
.B coords 
- coordinates of calling process in cartesian structure 
(array of integer) 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Cart_get ( comm, maxdims, dims, periods, coords )
MPI_Comm comm;
int maxdims;
int *dims, *periods, *coords;

.fi

.SH LOCATION
 cart_get.c
