.TH MPI_Start 3 "10/24/1994" " " "MPI"
.SH NAME
MPI_Start \- Initiates a communication with a persistent request handle

.SH INPUT PARAMETER
.PD 0
.TP
.B request 
- communication request (handle) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Start( request )
MPI_Request *request;

.fi

.SH LOCATION
 start.c
