.TH MPI_Testsome 3 "1/11/1996" " " "MPI"
.SH NAME
MPI_Testsome \- Tests for some given communications to complete

.SH INPUT PARAMETERS
.PD 0
.TP
.B incount 
- length of array_of_requests (integer) 
.PD 1
.PD 0
.TP
.B array_of_requests 
- array of requests (array of handles) 
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B outcount 
- number of completed requests (integer) 
.PD 1
.PD 0
.TP
.B array_of_indices 
- array of indices of operations that 
completed (array of integers) 
.PD 1
.PD 0
.TP
.B array_of_statuses 
- array of status objects for 
operations that completed (array of Status) 
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 
.I MPI_WTIME
and 
.I MPI_WTICK
) have
an additional argument 
.I ierr
at the end of the argument list.  
.I ierr
is an integer and has the same meaning as the return value of the routine
in C.  In Fortran, MPI routines are subroutines, and are invoked with the
.I call
statement.

All MPI objects (e.g., 
.I MPI_Datatype
, 
.I MPI_Comm
) are of type 
.I INTEGER
in Fortran.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Testsome( incount, array_of_requests, outcount, array_of_indices, 
    array_of_statuses )
int         incount, *outcount, array_of_indices[];
MPI_Request array_of_requests[];
MPI_Status  array_of_statuses[];

.fi

.SH LOCATION
 testsome.c
