.TH MPI_Op_free 3 "7/26/1994" " " "MPI"
.SH NAME
MPI_Op_free \- Frees a user-defined combination function handle

.SH INPUT PARAMETER
.PD 0
.TP
.B op 
- operation (handle) 
.PD 1

.SH NOTES
op is set to MPI_OP_NULL on exit.
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Op_free( op )
MPI_Op  *op;

.fi

.SH LOCATION
 opfree.c
