.TH MPI_Graph_get 3 "8/10/1994" " " "MPI"
.SH NAME
MPI_Graph_get \- Retrieves graph topology information associated with a
communicator

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator with graph structure (handle) 
.PD 1
.PD 0
.TP
.B maxindex 
- length of vector index in the calling program  (integer) 
.PD 1
.PD 0
.TP
.B maxedges 
- length of vector edges in the calling program  (integer) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B index 
- array of integers containing the graph structure (for details see the definition of MPI_GRAPH_CREATE ) 
.PD 1
.PD 0
.TP
.B edges 
- array of integers containing the graph structure 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Graph_get ( comm, maxindex, maxedges, index, edges )
MPI_Comm comm;
int maxindex, maxedges;
int *index, *edges;

.fi

.SH LOCATION
 graph_get.c
