.TH MPI_Cart_rank 3 "12/15/1994" " " "MPI"
.SH NAME
MPI_Cart_rank \- Determines process rank in communicator given Cartesian
location

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator with cartesian structure (handle) 
.PD 1
.PD 0
.TP
.B coords 
- integer array (of size  ndims ) specifying the cartesian coordinates of a process 
Output Parameter:
.PD 1
.PD 0
.TP
.B rank 
- rank of specified process (integer) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Cart_rank ( comm, coords, rank )
MPI_Comm comm;
int *coords;
int *rank;

.fi

.SH LOCATION
 cart_rank.c
