.TH MPI_Startall 3 "12/15/1994" " " "MPI"
.SH NAME
MPI_Startall \- Starts a collection of requests

.SH INPUT PARAMETERS
.PD 0
.TP
.B count 
- list length (integer) 
.PD 1
.PD 0
.TP
.B array_of_requests 
- array of requests (array of handle) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Startall( count, array_of_requests )
int count;
MPI_Request array_of_requests[];

.fi

.SH LOCATION
 startall.c
