.TH MPI_Errhandler_set 3 "12/15/1994" " " "MPI"
.SH NAME
MPI_Errhandler_set \- Sets the error handler for a communicator

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator to set the error handler for (handle) 
.PD 1
.PD 0
.TP
.B errhandler 
- new MPI error handler for communicator (handle) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Errhandler_set( comm, errhandler )
MPI_Comm       comm;
MPI_Errhandler errhandler;

.fi

.SH LOCATION
 errset.c
