.TH MPI_Wtime 3 "9/21/1994" " " "MPI"
.SH NAME
MPI_Wtime \- Returns an elapsed time on the calling processor

.SH RETURN VALUE
Time in seconds since an arbitrary time in the past.

.SH NOTES
This is intended to be a high-resolution, elapsed (or wall) clock.
See MPI_WTICK to determine the resolution of MPI_WTIME.
.SH SYNOPSIS
.nf
#include "mpi.h"
double MPI_Wtime()

.fi

.SH LOCATION
 wtime.c
