.TH MPI_Ibsend 3 "9/13/1995" " " "MPI"
.SH NAME
MPI_Ibsend \- Starts a nonblocking buffered send

.SH INPUT PARAMETERS
.PD 0
.TP
.B buf 
- initial address of send buffer (choice) 
.PD 1
.PD 0
.TP
.B count 
- number of elements in send buffer (integer) 
.PD 1
.PD 0
.TP
.B datatype 
- datatype of each send buffer element (handle) 
.PD 1
.PD 0
.TP
.B dest 
- rank of destination (integer) 
.PD 1
.PD 0
.TP
.B tag 
- message tag (integer) 
.PD 1
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B request 
- communication request (handle) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Ibsend( buf, count, datatype, dest, tag, comm, request )
void             *buf;
int              count;
MPI_Datatype     datatype;
int              dest;
int              tag;
MPI_Comm         comm;
MPI_Request      *request;

.fi

.SH LOCATION
 ibsend.c
