.TH MPI_Reduce_scatter 3 "12/15/1994" " " "MPI"
.SH NAME
MPI_Reduce_scatter \- Combines values and scatters the results

.SH INPUT PARAMETERS
.PD 0
.TP
.B sendbuf 
- starting address of send buffer (choice) 
.PD 1
.PD 0
.TP
.B recvcounts 
- integer array specifying the 
number of elements in result distributed to each process.
Array must be identical on all calling processes. 
.PD 1
.PD 0
.TP
.B datatype 
- data type of elements of input buffer (handle) 
.PD 1
.PD 0
.TP
.B op 
- operation (handle) 
.PD 1
.PD 0
.TP
.B comm 
- communicator (handle) 
.PD 1

.SH OUTPUT PARAMETER
.PD 0
.TP
.B recvbuf 
- starting address of receive buffer (choice) 
.PD 1
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Reduce_scatter ( sendbuf, recvbuf, recvcnts, datatype, op, comm )
void             *sendbuf;
void             *recvbuf;
int              *recvcnts;
MPI_Datatype      datatype;
MPI_Op            op;
MPI_Comm          comm;

.fi

.SH LOCATION
 red_scat.c
