.TH MPI_Attr_delete 3 "7/24/1995" " " "MPI"
.SH NAME
MPI_Attr_delete \- Deletes attribute value associated with a key

.SH INPUT PARAMETERS
.PD 0
.TP
.B comm 
- communicator to which attribute is attached (handle) 
.PD 1
.PD 0
.TP
.B keyval 
- The key value of the deleted attribute (integer) 
.PD 1

.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_Attr_delete ( comm, keyval )
MPI_Comm comm;
int      keyval;

.fi

.SH LOCATION
 attr_delval.c
