.TH MPIR_fstr2cstr 3 "12/9/1996" " " "MPI"
.SH NAME
MPIR_fstr2cstr \-  onvert a Fortran string into a C string. 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPIR_fstr2cstr (res, reslen, src, srclen)
char * res;
long reslen;
char *src;
long srclen;
.fi
.SH INPUT PARAMETERS
.  res     - Pointer to the result space
.PD 0
.TP
.B resLen  
- Length of result space
.PD 1
.PD 0
.TP
.B src     
- The Fortran string
.PD 1
.PD 0
.TP
.B srcLen  
- Length of the Fortran string
.PD 1

The result is 1 if the assignment was possible without truncation,
zero otherwise.

Trailing blanks are removed from the Fortran string.
.SH LOCATION
fstrutils.c
