.TH MPIR_Init 3 "7/1/1998" " " "MPI"
.SH NAME
MPIR_Init \-  Initialize the MPI execution environment 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPIR_Init(argc,argv)
int  *argc;
char ***argv;
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B argc 
- Pointer to the number of arguments 
.PD 1
.PD 0
.TP
.B argv 
- Pointer to the argument vector
.PD 1

See MPI_Init for the description of the input to this routine.

This routine is in a separate file form MPI_Init to allow profiling
libraries to not replace MPI_Init; without this, you can get errors
from the linker about multiply defined libraries.

.SH LOCATION
initutil.c
