#! /bin/sh
#
# Take the input file name and remove Chameleon statements, writing to stdout
if [ -n "$1" ] ; then
    sed -e '/#PVM3_START#/,/#PVM3_END#/d' \
	-e '/#CHAMELEON_START#/,/#CHAMELEON_END#/d' $1
else
    sed -e '/#PVM3_START#/,/#PVM3_END#/d' \
	-e '/#CHAMELEON_START#/,/#CHAMELEON_END#/d'
fi
