#! /bin/sh
#
# Take the input file name and remove code for heterogeneous processing, 
#  writing to stdout
if [ -n "$1" ] ; then 
    sed -e '/#HETERO_START#/,/#HETERO_END#/d' $1
else
    sed -e '/#HETERO_START#/,/#HETERO_END#/d'
fi
