#! /bin/sh
#
# Take the input file name and remove code for non-shared memory
# (MPID_USE_GET) processing, 
#  writing to stdout
if [ -n "$1" ] ; then 
    sed -e '/#NONGET_START#/,/#NONGET_END#/d' -e 's%/\*#GET_START#\*/%%g' \
	-e 's%/\*#GET_END#\*/%%g' $1
else
    sed -e '/#NONGET_START#/,/#NONGET_END#/d' -e 's%/\*#GET_START#\*/%%g' \
	-e 's%/\*#GET_END#\*/%%g'
fi
