#! /bin/sh
#
# Run some of the tests.  If any arguments are provided, pass them to the
# test programs.
#
# -mvhome is needed for the ANL SP, and is ignored by others
args="-pg -mvhome"
#
# If the programs are not available, run make.
#
runtests=1
makeeach=0
for arg in "$@" ; do
    case $arg in 
	-checkonly )
	runtests=0
	;;
        -margs=*)
	margs=`echo $arg | sed 's/-margs=//'`
	args="$args $margs"
	;;
	-small)
	makeeach=1
	;;
	-help|-u)
	echo "runtests [-checkonly] [-margs='...'] [-small]"
	echo "run tests in this directory.  If -checkonly set, just run"
	echo "the differences check (do NO rerun the test programs)."
	echo "If -margs is used, these options are passed to mpirun."
	echo "If -small is used, the examples are built, run, and deleted."
	exit 1
	;;
	*)
	if test -n "$arg" ; then
   	    echo "runtests: Unknown argument ($arg)"
	    exit 1
        fi
	;;
    esac
done

MakeExe() {
    if [ ! -x $1 ] ; then
	make $1
    fi
}
CleanExe() {
    if [ $makeeach = 1 ] ; then
	/bin/rm -f $1 $1.o
    fi
}

if [ ! -x cart -a $makeeach = 0 ] ; then
    make default
fi

testfiles=""
if [ $runtests = 1 ] ; then

testfiles="$testfiles cart.out"
/bin/rm -f cart.out
MakeExe cart
echo '**** Testing MPI_Cart_create etc ****' >> cart.out
echo '**** Testing MPI_Cart_create etc ****' 
mpirun $args -np 4 cart $* >> cart.out 2>&1
echo '**** Testing MPI_Cart_create etc ****' >> cart.out
CleanExe cart
#
testfiles="$testfiles cart2.out"
/bin/rm -f cart2.out
MakeExe cart2
echo '**** Testing MPI_Cart_coords etc ****' >> cart2.out
echo '**** Testing MPI_Cart_coords etc ****' 
mpirun $args -np 4 cart2 $* >> cart2.out 2>&1
echo '**** Testing MPI_Cart_coords etc ****' >> cart2.out
CleanExe cart2
#
# Run Fortran tests ONLY if Fortran available
if [ 1 = 1 ] ; then 
    echo "FORTRAN TESTS"
    #
    #
    testfiles="$testfiles cartf.out"
    /bin/rm -f cartf.out
    MakeExe cartf
    echo '*** Testing cart from Fortran ***'
    echo '*** Testing cart from Fortran ***' >> cartf.out
    mpirun $args -np 4 cartf "$@" >> cartf.out
    echo '*** Testing cart from Fortran ***' >> cartf.out
    CleanExe
    #
    testfiles="$testfiles cart1f.out"
    /bin/rm -f cart1f.out
    MakeExe cart1f
    echo '*** Testing cart1 from Fortran ***'
    echo '*** Testing cart1 from Fortran ***' >> cart1f.out
    mpirun $args -np 4 cart1f "$@" >> cart1f.out
    echo '*** Testing cart1 from Fortran ***' >> cart1f.out
    CleanExe
    #
    testfiles="$testfiles cart2f.out"
    /bin/rm -f cart2f.out
    MakeExe cart2f
    echo '*** Testing cart2 from Fortran ***'
    echo '*** Testing cart2 from Fortran ***' >> cart2f.out
    mpirun $args -np 4 cart2f "$@" >> cart2f.out
    echo '*** Testing cart2 from Fortran ***' >> cart2f.out
    CleanExe
    #
    testfiles="$testfiles twod.out"
    /bin/rm -f twod.out
    MakeExe twod
    echo '*** Testing twod from Fortran ***'
    echo '*** Testing twod from Fortran ***' >> twod.out
    mpirun $args -np 2 twod "$@" >> twod.out
    echo '*** Testing twod from Fortran ***' >> twod.out
    CleanExe
fi
else
    # Just run checks
    testfiles=*.out
fi
#
echo '*** Differences from expected output ***'
/bin/rm -f topol.diff
for file in $testfiles ; do
    stdfile=`basename $file .out`.std
    if [ -s $stdfile ] ; then
        if diff -b $file `basename $file .out`.std > /dev/null ; then
	    true
        else
	    echo "Differences in `basename $file .out`" >> topol.diff
	    diff -b $file `basename $file .out`.std >> topol.diff
	fi
    else
        echo "Can not find file $stdfile to compare against for test `basename $file .out`"
    fi
done
if [ -s topol.diff ] ; then
   cat topol.diff
fi
exit 0
