.TH MPE_Line_thickness 4 "6/8/1995" " " "MPE"
.SH NAME
MPE_Line_thickness \- set thickness of lines

.SH INPUT PARAMETERS
.PD 0
.TP
.B graph 
- MPE graphics handle
.PD 1
.PD 0
.TP
.B thickness 
- integer specifying how many pixels wide lines should be
.PD 1

.SH SYNOPSIS
.nf
#include <stdio.h>
#include "mpe.h"
int MPE_Line_thickness( graph, thickness )
MPE_XGraph graph;
int thickness;

.fi

.SH LOCATION
 mpe_graphics.c
