.TH MPE_Draw_string 4 "1/31/1997" " " "MPE"
.SH NAME
MPE_Draw_string \-  Input Parameters: . graph - MPE graphics handle . x - x-coordinate of the origin of the string . y - y-coordinate of the origin of the string . color - color of the text . string - text string to be drawn 
.SH SYNOPSIS
.nf
#include <stdio.h>
#include "mpe.h"

int MPE_Draw_string( graph, x, y, color, string )
MPE_XGraph graph;
int x, y;
MPE_Color color;
char *string;
.fi
.SH LOCATION
mpe_graphics.c
