.TH MPE_Signals_call_debugger 4 "7/1/1998" " " "MPE"
.SH NAME
MPE_Signals_call_debugger \-  Process-killing signals invoke the MPE error handler 
.SH SYNOPSIS
.nf
#include <stdio.h>
#include "mpe.h"
void MPE_Signals_call_debugger()
.fi
.SH NOTES
This invokes the MPE error handler which prints some information
about the signal and then attempts to start the debugger.  Some
systems will not support calling the debugger.

You may need to ignore some signals, depending on the signals that
the MPICH and underlying communications code is using.  You can
do this in dbx by adding "
.I ignore signal-name
" to your .dbxinit file.
For example, to ignore 
.I SIGUSR1
, use "
.I ignore USR1
".

Currently, there is no Fortran interface for this routine.
.SH LOCATION
dbxerr.c
