.TH MPE_Draw_line 4 "1/16/1996" " " "MPE"
.SH NAME
MPE_Draw_line \- Draws a line on an X11 display

.SH INPUT PARAMETERS
.PD 0
.TP
.B handle 
- MPE graphics handle 
.PD 1
.PD 0
.TP
.B x1,y1 
- pixel position of one end of the line to draw.  Coordinates are 
upper-left origin (standard X11)
.PD 1
.PD 0
.TP
.B x2,y2 
- pixel position of the other end of the line to draw.  Coordinates 
are upper-left origin (standard X11)
.PD 1
.PD 0
.TP
.B color 
- Color `index` value.  See 'MPE_MakeColorArray'.  
By default, the colors
'MPE_WHITE', 'MPE_BLACK', 'MPE_RED', 'MPE_YELLOW', 'MPE_GREEN', 'MPE_CYAN',
'MPE_BLUE',  'MPE_MAGENTA', 'MPE_AQUAMARINE', 
'MPE_FORESTGREEN', 'MPE_ORANGE', 'MPE_VIOLET', 'MPE_BROWN', 
'MPE_PINK', 'MPE_CORAL' and 'MPE_GRAY' are defined.
.PD 1
.SH SYNOPSIS
.nf
#include <stdio.h>
#include "mpe.h"
int MPE_Draw_line( handle, x1, y1, x2, y2, color )
MPE_XGraph handle;
int        x1, y1, x2, y2;
MPE_Color  color;

.fi

.SH LOCATION
 mpe_graphics.c
