#! /bin/sh
if [ -s ../../../aclocal.m4 -a -s ../../../aclocal_tcl.m4 ] ; then
    ln -s ../../../aclocal.m4
    ln -s ../../../aclocal_tcl.m4
    autoconf-1.7
    rm -f aclocal.m4 aclocal_tcl.m4
elif [ -s /home/gropp/tmp/cvstesting/mpich/aclocal.m4 ] ; then
    ln -s /home/gropp/tmp/cvstesting/mpich/aclocal.m4
    ln -s /home/gropp/tmp/cvstesting/mpich/aclocal_tcl.m4
    autoconf-1.7
    rm -f aclocal.m4 aclocal_tcl.m4
else
    echo "Unable to rebuild nupshot configure without aclocal.m4 and"
    echo "aclocal_tcl.m4 from MPICH1 distribution."
    echo "You should use jumpshot anyway; nupshot is not required for MPICH2"
fi
