#define PATCHLEVEL 1.2
#define PATCHLEVEL_MAJOR 1
#define PATCHLEVEL_MINOR 2
#define PATCHLEVEL_SUBMINOR 5
#define PATCHLEVEL_RELEASE_KIND "release first patches (1a)"
#define PATCHLEVEL_RELEASE_DATE "2003/01/24"
#ifndef PATCHLEVEL_RELEASE_DATE
#ifdef RELEASE_DATE
#define PATCHLEVEL_RELEASE_DATE RELEASE_DATE
#else
#define PATCHLEVEL_RELEASE_DATE "$Date: 2003/01/13 16:21:53$"
#endif
#endif

#define PATCHES_APPLIED "\
"
