#! /bin/sh
#
# This script derives the nexus routines from the Chameleon ones.  Some editing 
# of the files may be required after this process, but the goal is to 
# fully automate this process.
#
#/bin/cp ../chameleon/*.c .
sed -e '/#define DEVICE_CHAMELEON/d' \
    -e 's/MPID_CH/MPID_NEXUS/g' \
    -e 's/"Chameleon"/"Intel NEXUS"/g' ../chameleon/dmch.h > dmnexus.h
sed -e 's/MPID_CH/MPID_NEXUS/g' ../chameleon/mpid_bind.h > mpid_bind.h
sed -e 's/MPID_CH/MPID_NEXUS/g' ../chameleon/packets.h > packets.h
sed -e 's/MPID_CH/MPID_NEXUS/g' ../chameleon/mpiddebug.h > mpiddebug.h
sed -e 's/MPID_CH/MPID_NEXUS/g' ../chameleon/mpidstat.h > mpidstat.h
../chameleon/rmhetero ../chameleon/chevent.c > nexusevent.c
../chameleon/rmhetero ../chameleon/chrecv.c  > nexusrecv.c
../chameleon/rmhetero ../chameleon/chsend.c  > nexussend.c
../chameleon/rmhetero ../chameleon/chinit.c  > nexusinit.c
../chameleon/rmhetero ../chameleon/chprobe.c > nexusprobe.c
../chameleon/rmhetero ../chameleon/chsync.c  > nexussync.c
../chameleon/rmhetero ../chameleon/chrndv.c  > nexusrndv.c
../chameleon/rmhetero ../chameleon/chcoll.c  > nexuscoll.c
../chameleon/rmhetero ../chameleon/chdebug.c > nexusdebug.c
chmod ug+w *.[ch]
/home/gropp/tools.n/bin/inlinecomm -main -quiet -nexus nexusinit.c
for file in nexusevent.c nexusrecv.c nexussend.c nexusprobe.c nexussync.c \
  nexusrndv.c nexuscoll.c nexusdebug.c dmnexus.h packets.h ; do
    /home/gropp/tools.n/bin/inlinecomm -quiet -nexus $file
done
#
# Change the names MPID_CH to MPID_NEXUS
/bin/rm -f .tmp
for file in *.c ; do
    sed -e 's/MPID_CH/MPID_NEXUS/g' $file > .tmp
    mv .tmp $file
done

# Add in the small bit of functionality to MPID_Init() in nexusinit.c
patch nexusinit.c nexusinit.patch
patch dmnexus.h dmnexus.patch
# Get the the good copy of channel.h && nexuspriv.[ch]
# cp /necessary/files/from/someplace .
# currently already assumed to be in this directory with the patches :)
# Need this symbolic link for something...
ln -fs dmnexus.h dm.h
