#! /bin/sh
#
# This script derives the CMMD routines from the Chameleon ones.  Some editing 
# of the files may be required after this process, but the goal is to 
# fully automate this process.
#
# Remove old files
FILELIST="cmmdevent.c cmmdrecv.c cmmdsend.c cmmdprobe.c cmmdsync.c \
	cmmdrndv.c cmmddebug.c dmcmmd.h packets.h channel.h"
for file in $FILELIST ; do
    /bin/rm -f $file
done
sed -e '/#define DEVICE_CHAMELEON/d' \
    -e 's/MPID_CH/MPID_CMMD/g' \
    -e 's%"Chameleon"%"TMC cm5/cmmd"%g' \
    -e 's%/\* #CMMD DECLARATION# \*/%#include <cm/cmmd.h>%g' \
	 ../chameleon/dmch.h > dmcmmd.h

sed -e 's/MPID_CH/MPID_CMMD/g' ../chameleon/mpid_bind.h > mpid_bind.h
sed -e 's/MPID_CH/MPID_CMMD/g' ../chameleon/packets.h > packets.h
sed -e 's/MPID_CH/MPID_CMMD/g' ../chameleon/channel.h > channel.h
sed -e 's/MPID_CH/MPID_CMMD/g' ../chameleon/mpiddebug.h > mpiddebug.h
sed -e 's/MPID_CH/MPID_CMMD/g' ../chameleon/mpidstat.h > mpidstat.h
../chameleon/rmhetero ../chameleon/chevent.c > cmmdevent.c
../chameleon/rmhetero ../chameleon/chrecv.c  > cmmdrecv.c
../chameleon/rmhetero ../chameleon/chsend.c  > cmmdsend.c
../chameleon/rmhetero ../chameleon/chinit.c  | \
    sed -e 's%/\* #CMMD DECLARATION# \*/%#include <sys/file.h>%g' > cmmdinit.c
../chameleon/rmhetero ../chameleon/chprobe.c > cmmdprobe.c
../chameleon/rmhetero ../chameleon/chsync.c  > cmmdsync.c
../chameleon/rmhetero ../chameleon/chrndv.c  > cmmdrndv.c
../chameleon/rmhetero ../chameleon/chdebug.c  > cmmddebug.c
chmod ug+w *.[ch]
/home/gropp/tools.n/bin/inlinecomm -main -quiet -cm5 cmmdinit.c
for file in $FILELIST ; do
    /home/gropp/tools.n/bin/inlinecomm -quiet -cm5 $file
done
#
# Change the names MPID_CH to MPID_CMMD
/bin/rm -f .tmp
for file in $FILELIST ; do
    sed -e 's/MPID_CH/MPID_CMMD/g' $file > .tmp
    mv .tmp $file
    chmod a-w $file
done
