#!/bin/sh
# Nexus debugger script for gdb.
#
GDB=/usr/local/bin/gdb
#XTERM=/usr/bin/X11/xterm
#GDB=/bin/gdb
XTERM=/usr/local/X11R5/bin/xterm
RM="/bin/rm -f"
TMP=/tmp/nexus.debug.$$
TITLE="$0:  gdb $NEXUS_DEBUG_CONTEXT"
trap "$RM $TMP; exit 1" 1 2 15
export NEXUS_DEBUG_CONTEXT
export NEXUS_DEBUG_ARGS
export NEXUS_DEBUG_DISPLAY
echo "define go" > $TMP
echo "run $NEXUS_DEBUG_ARGS" >> $TMP
echo "end" >> $TMP
$XTERM -title "$TITLE" -display $NEXUS_DEBUG_DISPLAY \
    -e $GDB -command $TMP \
    $NEXUS_DEBUG_CONTEXT
$RM $TMP
