#! /bin/sh
#
# This script derives the eui routines from the Chameleon ones.  Some editing 
# of the files may be required after this process, but the goal is to 
# fully automate this process.
#
/bin/cp ../chameleon/*.c .
sed -e '/#define DEVICE_CHAMELEON/d' \
    -e 's/MPID_CH/MPID_EUI/g' \
    -e 's%"Chameleon"%"IBM EUI/EUIH"%g' ../chameleon/dmch.h > dmeui.h
sed -e 's/MPID_CH/MPID_EUI/g' ../chameleon/mpid_bind.h > mpid_bind.h
sed -e 's/MPID_CH/MPID_EUI/g' ../chameleon/packets.h > packets.h
mv chevent.c euievent.c
mv chrecv.c  euirecv.c
mv chsend.c  euisend.c
mv chinit.c  euiinit.c
mv chprobe.c euiprobe.c
mv chsync.c  euisync.c
chmod ug+w *.[ch]
/home/gropp/tools.n/bin/inlinecomm -main -quiet -euih euiinit.c
for file in euievent.c euirecv.c euisend.c euiprobe.c euisync.c dmeui.h \
	packets.h ; do
    /home/gropp/tools.n/bin/inlinecomm -quiet -euih $file
done
#
# Change the names MPID_CH to MPID_EUI
/bin/rm -f .tmp
for file in *.c ; do
    sed -e 's/MPID_CH/MPID_EUI/g' $file > .tmp
    mv .tmp $file
done
