#! /bin/sh
#
# This script derives the eui routines from the Chameleon ones.  Some editing 
# of the files may be required after this process, but the goal is to 
# fully automate this process.
#
sed -e '/#define DEVICE_CHAMELEON/d' \
    -e 's/MPID_CH_/MPID_EUI_/g' \
    -e 's%"Chameleon"%"IBM EUI/EUIH"%g' ../chameleon/dmch.h > dmeui.h
sed -e 's/MPID_CH_/MPID_EUI_/g' ../chameleon/mpid_bind.h > mpid_bind.h
sed -e 's/MPID_CH_/MPID_EUI_/g' ../chameleon/packets.h > packets.h
sed -e 's/MPID_CH_/MPID_EUI_/g' ../chameleon/channel.h > channel.h
sed -e 's/MPID_CH_/MPID_EUI_/g' ../chameleon/mpiddebug.h > mpiddebug.h
sed -e 's/MPID_CH_/MPID_EUI_/g' ../chameleon/mpidstat.h > mpidstat.h
for file in event recv send init probe sync rndv coll debug ; do 
    ../chameleon/rmhetero ../chameleon/ch$file.c | ../chameleon/rmget | \
	../chameleon/rmchameleon > eui$file.c
    chmod ug+w eui$file.c
done
chmod ug+w *.[ch]
/home/gropp/tools.n/bin/inlinecomm -main -quiet -euih euiinit.c
for file in euievent.c euirecv.c euisend.c euiprobe.c euisync.c dmeui.h \
	euirndv.c euicoll.c euidebug.c packets.h channel.h ; do
    /home/gropp/tools.n/bin/inlinecomm -quiet -euih $file
done
#
# Change the names MPID_CH to MPID_EUI
/bin/rm -f .tmp
for file in eui*.c ; do
    sed -e 's/MPID_CH_/MPID_EUI_/g' $file > .tmp
    mv .tmp $file
done
