# prototype makefile for util directory of P4

RM = rm

defs.MD: install.awk defs.all makefile.proto
	@if grep $(P4ARCH) machines > /dev/null ;\
	then \
	echo making machine-dependent definitions for $(P4ARCH) ;\
	awk -f install.awk machine=$(P4ARCH) defs.all > defs.MD ;\
	else \
	echo cannot install for $(P4ARCH), valid machines are: ;\
	cat machines ;\
	exit 1 ;\
	fi

default:

all:

realclean:
	$(RM) -f Makefile defs.MD *~ *.o
