#! /bin/sh
#
# This script derives the shmem routines from the Chameleon ones.  Some editing 
# of the files may be required after this process, but the goal is to 
# fully automate this process.
#
sed -e '/#define DEVICE_CHAMELEON/d' \
    -e 's/MPID_CH_/MPID_SHMEM_/g' \
    -e 's/"Chameleon"/"SHMEM"/g' ../chameleon/dmch.h > dmshmem.h
sed -e 's/MPID_CH_/MPID_SHMEM_/g' ../chameleon/mpid_bind.h > mpid_bind.h
sed -e 's/MPID_CH_/MPID_SHMEM_/g' ../chameleon/packets.h > packets.h
sed -e 's/MPID_CH_/MPID_SHMEM_/g' ../chameleon/mpiddebug.h > mpiddebug.h
sed -e 's/MPID_CH_/MPID_SHMEM_/g' ../chameleon/mpidstat.h > mpidstat.h
# Note that we do NOT include chcoll.c  in the list
for file in event recv send init probe sync get debug ; do 
    ../chameleon/rmhetero ../chameleon/ch$file.c | ../chameleon/rmnonget | \
	../chameleon/rmchameleon > shmem$file.c
    chmod ug+w shmem$file.c
done
chmod ug+w dmshmem.h mpid_bind.h packets.h 
#
# Update the few Chameleon calls remaining 
# Also, change MPID_SHMEM_WTIME to MPID_WTIME, incase MPID_WTIME is 
# inlined
# shmeminit
sed -e 's/PIiInit( argc, argv )/MPID_SHMEM_init( argc, *argv );/g' \
    -e 's/PIiFinish()/MPID_SHMEM_finalize()/g' \
    -e 's%#include "system/system.h"%%g' \
    -e 's%/\* #CMMD DECLARATION# \*/%%g' \
    -e 's/PINodeName/SY_GetHostName/g' \
    -e 's/SYSetResourceClockOff()//g' \
    -e 's/SYGetElapsedTime()/p2p_wtime()/g' \
    -e 's/MPID_SHMEM_WTIME()/MPID_WTIME((void*)0)/g' \
    -e 's/MPID_CH_WTIME()/MPID_WTIME((void *)0)/g' \
		shmeminit.c > .tmp	
mv .tmp shmeminit.c
#
# dmshmem.h
sed -e 's%#include "comm/comm.h"%#include "p2p.h"%g' \
    -e 's%#include "system/system.h"%%g' \
    -e 's%#include "system/time/usec.h"%%g' \
    -e 's/#include "tools.h"/#include <stdio.h>/g' \
    -e 's/ASYNCSendId_t/int/g' \
    -e 's/ASYNCRecvId_t/int/g' dmshmem.h > .tmp
mv .tmp dmshmem.h
#
# Change the names MPID_CH to MPID_SHMEM
/bin/rm -f .tmp
for file in shmem*.c ; do
    if [ "$file" = shmempriv.c ] ; then
        continue 
    fi
    sed -e 's/MPID_CH_/MPID_SHMEM_/g' $file > .tmp
    mv .tmp $file
done
