#! /bin/sh
#
# This script derives the shmem routines from the Chameleon ones.  Some editing 
# of the files may be required after this process, but the goal is to 
# fully automate this process.
#
sed -e '/#define DEVICE_CHAMELEON/d' \
    -e 's/MPID_CH/MPID_SHMEM/g' \
    -e 's/"Chameleon"/"SHMEM"/g' ../chameleon/dmch.h > dmshmem.h
sed -e 's/MPID_CH/MPID_SHMEM/g' ../chameleon/mpid_bind.h > mpid_bind.h
sed -e 's/MPID_CH/MPID_SHMEM/g' ../chameleon/packets.h > packets.h
../chameleon/rmhetero ../chameleon/chevent.c > shmemevent.c
../chameleon/rmhetero ../chameleon/chrecv.c  > shmemrecv.c
../chameleon/rmhetero ../chameleon/chsend.c  > shmemsend.c
../chameleon/rmhetero ../chameleon/chinit.c  > shmeminit.c
../chameleon/rmhetero ../chameleon/chprobe.c > shmemprobe.c
../chameleon/rmhetero ../chameleon/chsync.c  > shmemsync.c
../chameleon/rmhetero ../chameleon/chpkt.c   > shmempkt.c
../chameleon/rmhetero ../chameleon/chcoll.c  > shmemcoll.c
../chameleon/rmhetero ../chameleon/chrndv.c  > shmemrndv.c
../chameleon/rmhetero ../chameleon/chget.c  > shmemget.c
chmod ug+w shmemevent.c shmemrecv.c shmemsend.c shmeminit.c shmemprobe.c \
	   shmemsync.c shmempkt.c shmemrndv.c shmemget.c \
	   dmshmem.h mpid_bind.h packets.h shmemcoll.c
#
# Update the few Chameleon calls remaining (not yet done)
# shmeminit
sed -e 's/PIiInit( argc, argv )/MPID_SHMEM_init( argc, *argv );/g' \
    -e 's/PIiFinish()/MPID_SHMEM_finalize()/g' \
    -e 's%#include "system/system.h"%%g' \
    -e 's%/\* #CMMD DECLARATION# \*/%%g' \
    -e 's/PINodeName/SY_GetHostName/g' \
    -e 's/SYSetResourceClockOff()//g' \
    -e 's/SYGetElapsedTime()/p2p_wtime()/g' \
		shmeminit.c > .tmp	
mv .tmp shmeminit.c
#
# dmshmem.h
sed -e 's%#include "comm/comm.h"%#include "p2p.h"%g' \
    -e 's%#include "system/system.h"%%g' \
    -e 's%#include "system/time/usec.h"%%g' \
    -e 's/#include "tools.h"/#include <stdio.h>/g' \
    -e 's/ASYNCSendId_t/int/g' \
    -e 's/ASYNCRecvId_t/int/g' dmshmem.h > .tmp
mv .tmp dmshmem.h
#
# Change the names MPID_CH to MPID_SHMEM
/bin/rm -f .tmp
for file in shmem*.c ; do
    if [ "$file" = shmempriv.c ] ; then
        continue 
    fi
    sed -e 's/MPID_CH/MPID_SHMEM/g' $file > .tmp
    mv .tmp $file
done
